### ISSUE TITLE
Odd client crash if anything is changed in the blend

### ISSUE THREAD

**Issue by DoobesURU** [H-uru/korman#397] opened 2024-01-15 20:26 UTC
This is an odd anomaly that has cropped up with Chiso Preniv. When I change something and export, the client closes and gives this long list of error goodness:

```
UruLive.1.918 - 085186d - Internal.Release
OS: Windows 10 Home Edition Professional (Build 19045)
CPU: AMD FX(tm)-4300 Quad-Core Processor            
RAM: 16384 MiB

Stack Trace:
Level 00: plClient!__chkstk (File: chkstk.asm:109)
Level 01: plClient!physx::SubSortSAH::sort4 (File: RTreeCooking.cpp:547)
Level 02: plClient!physx::SubSortSAH::sort4 (File: RTreeCooking.cpp:707)
Level 03: plClient!physx::SubSortSAH::sort4 (File: RTreeCooking.cpp:707)
Level 04: plClient!physx::SubSortSAH::sort4 (File: RTreeCooking.cpp:707)
Level 05: plClient!physx::SubSortSAH::sort4 (File: RTreeCooking.cpp:707)
Level 06: plClient!physx::SubSortSAH::sort4 (File: RTreeCooking.cpp:707)
Level 07: plClient!physx::SubSortSAH::sort4 (File: RTreeCooking.cpp:707)
Level 08: plClient!physx::SubSortSAH::sort4 (File: RTreeCooking.cpp:707)
Level 09: plClient!physx::SubSortSAH::sort4 (File: RTreeCooking.cpp:707)
Level 10: plClient!physx::SubSortSAH::sort4 (File: RTreeCooking.cpp:707)
Level 11: plClient!physx::SubSortSAH::sort4 (File: RTreeCooking.cpp:707)
Level 12: plClient!physx::SubSortSAH::sort4 (File: RTreeCooking.cpp:707)
Level 13: plClient!physx::SubSortSAH::sort4 (File: RTreeCooking.cpp:707)
Level 14: plClient!physx::SubSortSAH::sort4 (File: RTreeCooking.cpp:707)
Level 15: plClient!physx::SubSortSAH::sort4 (File: RTreeCooking.cpp:707)
Level 16: plClient!physx::SubSortSAH::sort4 (File: RTreeCooking.cpp:707)
Level 17: plClient!physx::SubSortSAH::sort4 (File: RTreeCooking.cpp:707)
Level 18: plClient!physx::SubSortSAH::sort4 (File: RTreeCooking.cpp:707)
Level 19: plClient!physx::SubSortSAH::sort4 (File: RTreeCooking.cpp:707)
Level 20: plClient!physx::SubSortSAH::sort4 (File: RTreeCooking.cpp:707)
Level 21: plClient!physx::SubSortSAH::sort4 (File: RTreeCooking.cpp:707)
Level 22: plClient!physx::SubSortSAH::sort4 (File: RTreeCooking.cpp:707)
Level 23: plClient!physx::SubSortSAH::sort4 (File: RTreeCooking.cpp:707)
Level 24: plClient!physx::SubSortSAH::sort4 (File: RTreeCooking.cpp:707)
Level 25: plClient!physx::SubSortSAH::sort4 (File: RTreeCooking.cpp:707)
Level 26: plClient!physx::SubSortSAH::sort4 (File: RTreeCooking.cpp:707)
Level 27: plClient!physx::SubSortSAH::sort4 (File: RTreeCooking.cpp:707)
Level 28: plClient!physx::SubSortSAH::sort4 (File: RTreeCooking.cpp:707)
Level 29: plClient!physx::SubSortSAH::sort4 (File: RTreeCooking.cpp:707)
Level 30: plClient!physx::SubSortSAH::sort4 (File: RTreeCooking.cpp:707)
Level 31: plClient!physx::SubSortSAH::sort4 (File: RTreeCooking.cpp:707)
Level 32: plClient!physx::SubSortSAH::sort4 (File: RTreeCooking.cpp:707)
Level 33: plClient!physx::SubSortSAH::sort4 (File: RTreeCooking.cpp:707)
Level 34: plClient!physx::SubSortSAH::sort4 (File: RTreeCooking.cpp:707)
Level 35: plClient!physx::SubSortSAH::sort4 (File: RTreeCooking.cpp:707)
Level 36: plClient!physx::SubSortSAH::sort4 (File: RTreeCooking.cpp:707)
Level 37: plClient!physx::SubSortSAH::sort4 (File: RTreeCooking.cpp:707)
Level 38: plClient!physx::SubSortSAH::sort4 (File: RTreeCooking.cpp:707)
Level 39: plClient!physx::SubSortSAH::sort4 (File: RTreeCooking.cpp:707)
Level 40: plClient!physx::SubSortSAH::sort4 (File: RTreeCooking.cpp:707)
Level 41: plClient!physx::SubSortSAH::sort4 (File: RTreeCooking.cpp:707)
Level 42: plClient!physx::SubSortSAH::sort4 (File: RTreeCooking.cpp:707)
Level 43: plClient!physx::SubSortSAH::sort4 (File: RTreeCooking.cpp:707)
Level 44: plClient!physx::SubSortSAH::sort4 (File: RTreeCooking.cpp:707)
Level 45: plClient!physx::SubSortSAH::sort4 (File: RTreeCooking.cpp:707)
Level 46: plClient!physx::SubSortSAH::sort4 (File: RTreeCooking.cpp:707)
Level 47: plClient!physx::SubSortSAH::sort4 (File: RTreeCooking.cpp:707)
Level 48: plClient!physx::SubSortSAH::sort4 (File: RTreeCooking.cpp:707)
Level 49: plClient!physx::SubSortSAH::sort4 (File: RTreeCooking.cpp:707)
Level 50: plClient!physx::SubSortSAH::sort4 (File: RTreeCooking.cpp:707)
Level 51: plClient!physx::SubSortSAH::sort4 (File: RTreeCooking.cpp:707)
Level 52: plClient!physx::SubSortSAH::sort4 (File: RTreeCooking.cpp:707)
Level 53: plClient!physx::SubSortSAH::sort4 (File: RTreeCooking.cpp:707)
Level 54: plClient!physx::SubSortSAH::sort4 (File: RTreeCooking.cpp:707)
Level 55: plClient!physx::SubSortSAH::sort4 (File: RTreeCooking.cpp:707)
Level 56: plClient!physx::SubSortSAH::sort4 (File: RTreeCooking.cpp:707)
Level 57: plClient!physx::SubSortSAH::sort4 (File: RTreeCooking.cpp:707)
Level 58: plClient!physx::SubSortSAH::sort4 (File: RTreeCooking.cpp:707)
Level 59: plClient!physx::SubSortSAH::sort4 (File: RTreeCooking.cpp:707)
Level 60: plClient!physx::SubSortSAH::sort4 (File: RTreeCooking.cpp:707)
Level 61: plClient!physx::SubSortSAH::sort4 (File: RTreeCooking.cpp:707)
Level 62: plClient!physx::SubSortSAH::sort4 (File: RTreeCooking.cpp:707)
Level 63: plClient!physx::SubSortSAH::sort4 (File: RTreeCooking.cpp:707)
Level 64: plClient!physx::SubSortSAH::sort4 (File: RTreeCooking.cpp:707)
Level 65: plClient!physx::SubSortSAH::sort4 (File: RTreeCooking.cpp:707)
Level 66: plClient!physx::SubSortSAH::sort4 (File: RTreeCooking.cpp:707)
Level 67: plClient!physx::SubSortSAH::sort4 (File: RTreeCooking.cpp:707)
Level 68: plClient!physx::SubSortSAH::sort4 (File: RTreeCooking.cpp:707)
Level 69: plClient!physx::SubSortSAH::sort4 (File: RTreeCooking.cpp:707)
Level 70: plClient!physx::SubSortSAH::sort4 (File: RTreeCooking.cpp:707)
Level 71: plClient!physx::SubSortSAH::sort4 (File: RTreeCooking.cpp:707)
Level 72: plClient!physx::SubSortSAH::sort4 (File: RTreeCooking.cpp:707)
Level 73: plClient!physx::SubSortSAH::sort4 (File: RTreeCooking.cpp:707)
Level 74: plClient!physx::SubSortSAH::sort4 (File: RTreeCooking.cpp:707)
Level 75: plClient!physx::SubSortSAH::sort4 (File: RTreeCooking.cpp:707)
Level 76: plClient!physx::SubSortSAH::sort4 (File: RTreeCooking.cpp:707)
Level 77: plClient!physx::SubSortSAH::sort4 (File: RTreeCooking.cpp:707)
Level 78: plClient!physx::SubSortSAH::sort4 (File: RTreeCooking.cpp:707)
Level 79: plClient!physx::SubSortSAH::sort4 (File: RTreeCooking.cpp:707)
Level 80: plClient!physx::SubSortSAH::sort4 (File: RTreeCooking.cpp:707)
Level 81: plClient!physx::SubSortSAH::sort4 (File: RTreeCooking.cpp:707)
Level 82: plClient!physx::SubSortSAH::sort4 (File: RTreeCooking.cpp:707)
Level 83: plClient!physx::SubSortSAH::sort4 (File: RTreeCooking.cpp:707)
Level 84: plClient!physx::SubSortSAH::sort4 (File: RTreeCooking.cpp:707)
Level 85: plClient!physx::SubSortSAH::sort4 (File: RTreeCooking.cpp:707)
Level 86: plClient!physx::SubSortSAH::sort4 (File: RTreeCooking.cpp:707)
Level 87: plClient!physx::SubSortSAH::sort4 (File: RTreeCooking.cpp:707)
Level 88: plClient!physx::SubSortSAH::sort4 (File: RTreeCooking.cpp:707)
Level 89: plClient!physx::SubSortSAH::sort4 (File: RTreeCooking.cpp:707)
Level 90: plClient!physx::SubSortSAH::sort4 (File: RTreeCooking.cpp:707)
Level 91: plClient!physx::SubSortSAH::sort4 (File: RTreeCooking.cpp:707)
Level 92: plClient!physx::SubSortSAH::sort4 (File: RTreeCooking.cpp:707)
Level 93: plClient!physx::SubSortSAH::sort4 (File: RTreeCooking.cpp:707)
Level 94: plClient!physx::SubSortSAH::sort4 (File: RTreeCooking.cpp:707)
Level 95: plClient!physx::SubSortSAH::sort4 (File: RTreeCooking.cpp:707)
Level 96: plClient!physx::SubSortSAH::sort4 (File: RTreeCooking.cpp:707)
Level 97: plClient!physx::SubSortSAH::sort4 (File: RTreeCooking.cpp:707)
Level 98: plClient!physx::SubSortSAH::sort4 (File: RTreeCooking.cpp:707)
Level 99: plClient!physx::SubSortSAH::sort4 (File: RTreeCooking.cpp:707)
Level 100: plClient!physx::SubSortSAH::sort4 (File: RTreeCooking.cpp:707)
Level 101: plClient!physx::SubSortSAH::sort4 (File: RTreeCooking.cpp:707)
Level 102: plClient!physx::SubSortSAH::sort4 (File: RTreeCooking.cpp:707)
Level 103: plClient!physx::SubSortSAH::sort4 (File: RTreeCooking.cpp:707)
Level 104: plClient!physx::SubSortSAH::sort4 (File: RTreeCooking.cpp:707)
Level 105: plClient!physx::SubSortSAH::sort4 (File: RTreeCooking.cpp:707)
Level 106: plClient!physx::SubSortSAH::sort4 (File: RTreeCooking.cpp:707)
Level 107: plClient!physx::SubSortSAH::sort4 (File: RTreeCooking.cpp:707)
Level 108: plClient!physx::SubSortSAH::sort4 (File: RTreeCooking.cpp:707)
Level 109: plClient!physx::SubSortSAH::sort4 (File: RTreeCooking.cpp:707)
Level 110: plClient!physx::SubSortSAH::sort4 (File: RTreeCooking.cpp:707)
Level 111: plClient!physx::SubSortSAH::sort4 (File: RTreeCooking.cpp:707)
Level 112: plClient!physx::SubSortSAH::sort4 (File: RTreeCooking.cpp:707)
Level 113: plClient!physx::SubSortSAH::sort4 (File: RTreeCooking.cpp:707)
Level 114: plClient!physx::SubSortSAH::sort4 (File: RTreeCooking.cpp:707)
Level 115: plClient!physx::SubSortSAH::sort4 (File: RTreeCooking.cpp:707)
Level 116: plClient!physx::SubSortSAH::sort4 (File: RTreeCooking.cpp:707)
Level 117: plClient!physx::SubSortSAH::sort4 (File: RTreeCooking.cpp:707)
Level 118: plClient!physx::SubSortSAH::sort4 (File: RTreeCooking.cpp:707)
Level 119: plClient!physx::SubSortSAH::sort4 (File: RTreeCooking.cpp:707)
Level 120: plClient!physx::buildFromBounds (File: RTreeCooking.cpp:766)
Level 121: plClient!physx::RTreeCooker::buildFromTriangles (File: RTreeCooking.cpp:121)
Level 122: plClient!physx::RTreeTriangleMeshBuilder::createMidPhaseStructure (File: TriangleMeshBuilder.cpp:1345)
Level 123: plClient!physx::TriangleMeshBuilder::loadFromDesc (File: TriangleMeshBuilder.cpp:822)
Level 124: plClient!physx::Cooking::createTriangleMesh (File: Cooking.cpp:173)
Level 125: plClient!plPXPhysical::ICookTriMesh (File: plPXPhysical.cpp:582)
Level 126: plClient!plPXPhysical::Read (File: plGenericPhysical.cpp:379)
Level 127: plClient!plResManager::ReadCreatable (File: plResManager.cpp:953)
Level 128: plClient!plResManager::IReadObject (File: plResManager.cpp:427)
Level 129: plClient!plResManager::ReadObject (File: plResManager.cpp:333)
Level 130: plClient!plKeyImp::VerifyLoaded (File: plKeyImp.cpp:189)
Level 131: plClient!plResManager::ReadObject (File: plResManager.cpp:348)
Level 132: plClient!plKeyImp::VerifyLoaded (File: plKeyImp.cpp:189)
Level 133: plClient!plResManager::ReadObject (File: plResManager.cpp:348)
Level 134: plClient!plKeyImp::VerifyLoaded (File: plKeyImp.cpp:189)
Level 135: plClient!plResManager::ReadObject (File: plResManager.cpp:348)
Level 136: plClient!plKeyImp::VerifyLoaded (File: plKeyImp.cpp:189)
Level 137: plClient!plResManager::PageInRoom (File: plResManager.cpp:1214)
Level 138: plClient!plClient::ILoadNextRoom (File: plClient.cpp:1029)
Level 139: plClient!plClient::MsgReceive (File: plClient.cpp:847)
Level 140: plClient!plDispatch::IMsgDispatch (File: plDispatch.cpp:370)
Level 141: plClient!plDispatch::MsgSend (File: plDispatch.cpp:501)
Level 142: plClient!plMessage::Send (File: plMessage.cpp:100)
Level 143: plClient!plAgeLoader::ILoadAge (File: plAgeLoader.cpp:301)
Level 144: plClient!plNCAgeJoiner::ExecNextOp (File: plNetCliAgeJoiner.cpp:265)
Level 145: plClient!plNetClientMgr::Update (File: plNetClientMgr.cpp:465)
Level 146: plClient!plClient::IUpdate (File: plClient.cpp:1590)
Level 147: plClient!plClient::MainLoop (File: plClient.cpp:1521)
Level 148: plClient!WinMain (File: winmain.cpp:1307)
Level 149: plClient!__scrt_common_main_seh (File: exe_common.inl:288)
Level 150: KERNEL32!BaseThreadInitThunk
```

However, if I don't touch anything and re-export, the Age works fine. I did notice that this stops if I turn off the GUI note popup for the Memorial Island sketch, so it might have something to do with that mod?

In any case, I don't know if I can reproduce this, but I can provide the Chiso blend (which isn't nearly as big as it was since I shrank a lot of textures) upon request.

**Comment by Hoikas** [comment] 2024-01-15 20:45
This is probably an engine and/or PhysX bug. Can you share the PRP files that cause the crash?

**Comment by DoobesURU** [comment] 2024-01-15 20:48
> This is probably an engine and/or PhysX bug. Can you share the PRP files that cause the crash?

Certainly. I'll attempt to recreate some PRPs that crash and bundle them up in a bit.

**Comment by Hoikas** [comment] 2024-01-15 21:26
These PRPs work fine for me. I expect the problem is that Destiny's client is a bit out of date and has some kind of bug that Chiso is tripping. Anyway, this doesn't seem to be a Korman problem, so I'm going to close the issue here.

**Closed by Hoikas** 2024-01-15 21:26 UTC
